<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>m</string>
		<string>moo</string>
	</array>
	<key>name</key>
	<string>Mercury</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#string_quoted_double</string>
			<key>name</key>
			<string>string.quoted.double.source.mercury</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.source.mercury</string>
				</dict>
			</dict>
			<key>end</key>
			<string>'</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.source.mercury</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.single.source.mercury</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.source.mercury</string>
				</dict>
				<dict>
					<key>match</key>
					<string>''</string>
					<key>name</key>
					<string>constant.character.escape.quote.source.mercury</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>#block_comment</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#line_comment</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(:-) (impure)?\s*(pred|func|type|mode|inst|typeclass|instance) ([a-z][_\.a-zA-Z0-9]*)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.source.mercury</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.control.declaration.source.mercury</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.source.mercury</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=\.[ \t]*(\n|%))</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#decl_spec</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#decl_params</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#decl_keywords</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#determ_decl</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#common_ops</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#higher_order_insts</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#default_insts</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#poly_type_name</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#atom</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#type_name</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.source.mercury</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.other.declaration.source.mercury</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.module.source.mercury</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(:-) (use_module|import_module|end_module|module) ([a-z][_\.a-zA-Z0-9]*)\b</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.source.mercury</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.other.declaration.source.mercury</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(:-) (interface|implementation)\b</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(:-) (pragma) (foreign_[a-z_]+)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.source.mercury</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.other.pragma.foreign.source.mercury</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.language.pragma.source.mercury</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=\.[ \t]*(\n|%))</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#decl_keywords</string>
				</dict>
				<dict>
					<key>match</key>
					<string>^[ \t]*where\b</string>
					<key>name</key>
					<string>keyword.control.declaration.source.mercury</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\[</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.control.list.begin.source.mercury</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\]</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.control.list.end.source.mercury</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\b(will_not_modify_trail|will_not_call_mercury|promise_pure|thread_safe|does_not_affect_liveness|no_sharing|tabled_for_io|can_pass_as_mercury_type|may_not_duplicate)\b</string>
							<key>name</key>
							<string>constant.language.proc_type.source.mercury,</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#common_ops</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#block_comment</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#line_comment</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>#variable</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#default_insts</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#type_name</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>string.quoted.double.source.mercury</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.control.parens.begin.source.mercury</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.source.mercury</string>
						</dict>
					</dict>
					<key>match</key>
					<string>("C#"|csharp|"C"|c|"Erlang"|erlang|"Java"|java|"IL"|il)[,][ \t]*([(]?)([a-z][a-zA-Z0-9_\.]*)</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.parens.begin.source.mercury</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.source.mercury</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^[ \t]*(\()?([a-z][a-zA-Z0-9_\.]*)\b</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string_quoted_double</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#block_comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#line_comment</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>#decl_keywords</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^[a-z][a-zA-Z0-9_\.]*\b</string>
			<key>name</key>
			<string>entity.name.function.source.mercury</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#logic_consts</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#variable</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#impl_defined_variable</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#number</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#common_ops</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#atom</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#higher_order_insts</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#poly_type_name</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#list_block</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#logic_block</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>atom</key>
		<dict>
			<key>match</key>
			<string>\b[a-z][a-zA-Z0-9_]*\b</string>
			<key>name</key>
			<string>constant.other.symbol.source.mercury</string>
		</dict>
		<key>block_comment</key>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.source.mercury</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.source.mercury</string>
		</dict>
		<key>common_ops</key>
		<dict>
			<key>match</key>
			<string>(-(?![&gt;-])|&lt;=&gt;|&lt;=|=&lt;|&gt;=|=&gt;|-&gt;|--&gt;|---&gt;|[+](?![+])|[+][+](?![+])|[*](?![*])|[*][*](?![*])|,|;|/|//|=(?![=&lt;&gt;])|==|::|![\.:]?|:-|`)</string>
			<key>name</key>
			<string>keyword.operator.source.mercury</string>
		</dict>
		<key>decl_keywords</key>
		<dict>
			<key>match</key>
			<string>\b(is|where)\b</string>
			<key>name</key>
			<string>keyword.control.declaration.source.mercury</string>
		</dict>
		<key>decl_params</key>
		<dict>
			<key>begin</key>
			<string>\(</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.control.parens.begin.source.mercury</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\)</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.control.parens.end.source.mercury</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#decl_keywords</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#determ_decl</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#poly_insts</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#higher_order_insts</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#poly_type_name</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#default_insts</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#type_name</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#variable</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#common_ops</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#block_comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#line_comment</string>
				</dict>
			</array>
		</dict>
		<key>decl_spec</key>
		<dict>
			<key>begin</key>
			<string>\[</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.control.list.begin.source.mercury</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\]</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.control.list.end.source.mercury</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#higher_order_insts</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#decl_keywords</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#type_name</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#logic_block</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#common_ops</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#block_comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#line_comment</string>
				</dict>
			</array>
		</dict>
		<key>default_insts</key>
		<dict>
			<key>match</key>
			<string>\b(in|out|ui|di|uo|free|unique|ground)\b</string>
			<key>name</key>
			<string>constant.language.inst.source.mercury</string>
		</dict>
		<key>determ_decl</key>
		<dict>
			<key>match</key>
			<string>\b(multi|cc_multi|det|semidet|nondet|errorneous)\b</string>
			<key>name</key>
			<string>constant.language.determ.source.mercury</string>
		</dict>
		<key>higher_order_insts</key>
		<dict>
			<key>begin</key>
			<string>\b(pred|func)(\()</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.language.inst.source.mercury</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.control.parens.begin.source.mercury</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\)</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.control.parens.end.source.mercury</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#poly_insts</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#default_insts</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#variable</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#poly_type_name</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#higher_order_insts</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#type_name</string>
				</dict>
			</array>
		</dict>
		<key>impl_defined_vairable</key>
		<dict>
			<key>match</key>
			<string>[$][a-zA-Z0-9_]*\b</string>
			<key>name</key>
			<string>variable.language.source.mercury</string>
		</dict>
		<key>line_comment</key>
		<dict>
			<key>begin</key>
			<string>(^[ \t]+)?(%([-]+%)?)(.*)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.whitespace.comment.leading.source.mercury</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>comment.line.percentage.source.mercury</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?!\G)</string>
		</dict>
		<key>list_block</key>
		<dict>
			<key>begin</key>
			<string>\[</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.control.list.begin.source.mercury</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\]</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.control.list.end.source.mercury</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#string_quoted_double</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#block_comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#line_comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<key>logic_block</key>
		<dict>
			<key>begin</key>
			<string>(?=\W)(\()</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.parens.begin.source.mercury</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\)</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.control.parens.end.source.mercury</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#string_quoted_double</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#block_comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#line_comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<key>logic_consts</key>
		<dict>
			<key>match</key>
			<string>\b(yes|no|true|false|(semidet_)?succeed|(semidet_)?fail)\b</string>
			<key>name</key>
			<string>constant.language.logic.source.mercury</string>
		</dict>
		<key>number</key>
		<dict>
			<key>match</key>
			<string>\b(0[0-7]*|0'.|[1-9][0-9]*|\.[0-9]+([eE][0-9]+)?|0[xX][0-9a-fA-F]+|0[bB][01]+)\b</string>
			<key>name</key>
			<string>constant.numeric.source.mercury</string>
		</dict>
		<key>poly_insts</key>
		<dict>
			<key>begin</key>
			<string>\b(in|out|ui|uo|di|unique)(\()</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.language.inst.source.mercury</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.control.parens.begin.source.mercury</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\)</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.control.parens.end.source.mercury</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#higher_order_insts</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#default_insts</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#decl_keywords</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#determ_decl</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#atom</string>
				</dict>
			</array>
		</dict>
		<key>poly_type_name</key>
		<dict>
			<key>begin</key>
			<string>\b([a-z][_\.a-zA-Z0-9]*)\(</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.type.poly.source.mercury</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.control.parens.begin.source.mercury</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\)</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.control.parens.end.source.mercury</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#poly_type_name</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#variable</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#type_name</string>
				</dict>
			</array>
		</dict>
		<key>string_quoted_double</key>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.literal.string.begin.source.mercury</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.literal.string.end.source.mercury</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.source.mercury</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.source.mercury</string>
				</dict>
				<dict>
					<key>match</key>
					<string>""</string>
					<key>name</key>
					<string>constant.character.escape.quote.source.mercury</string>
				</dict>
			</array>
		</dict>
		<key>type_name</key>
		<dict>
			<key>match</key>
			<string>\b([a-z][_\.a-zA-Z0-9]*)\b</string>
			<key>name</key>
			<string>support.type.source.mercury</string>
		</dict>
		<key>variable</key>
		<dict>
			<key>match</key>
			<string>\b[A-Z][a-zA-Z0-9_]*\b</string>
			<key>name</key>
			<string>variable.other.source.mercury</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.mercury</string>
	<key>uuid</key>
	<string>A3E186F8-CF20-4983-B132-209EDF43E3DE</string>
</dict>
</plist>
