<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
	</array>
	<key>name</key>
	<string>Mercury</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#string_quoted_double</string>
			<key>name</key>
			<string>string.quoted.double.source.mercury</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.source.mercury</string>
				</dict>
			</dict>
			<key>end</key>
			<string>'</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.source.mercury</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.single.source.mercury</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.source.mercury</string>
				</dict>
				<dict>
					<key>match</key>
					<string>''</string>
					<key>name</key>
					<string>constant.character.escape.quote.source.mercury</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.source.mercury</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.source.mercury</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#line_comment</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>:- (impure)?\s*(pred|func|type|mode|inst|typeclass|instance) ([a-z][_\.a-zA-Z0-9]*)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.control.declaration.source.mercury</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.source.mercury</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=\.[ \t]*(\n|%))</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#default_insts</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#decl_keywords</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#determ_decl</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#type_name</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\(</string>
					<key>end</key>
					<string>\)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#variable</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#default_insts</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#decl_keywords</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#type_name</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\[</string>
					<key>end</key>
					<string>\]</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.declaration.source.mercury</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.module.source.mercury</string>
				</dict>
			</dict>
			<key>match</key>
			<string>:- (use_module|import_module|end_module|module) ([a-z][_\.a-zA-Z0-9]*)\b</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.declaration.source.mercury</string>
				</dict>
			</dict>
			<key>match</key>
			<string>:- (interface|implementation)\b</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>:- (pragma) (foreign_[a-z_]+)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.pragma.foreign.source.mercury</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.language.pragma.source.mercury</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=\.[ \t]*(\n|%))</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#decl_keywords</string>
				</dict>
				<dict>
					<key>match</key>
					<string>^[ \t]*where\b</string>
					<key>name</key>
					<string>keyword.control.declaration.source.mercury</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\[</string>
					<key>end</key>
					<string>\]</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>(will_not_call_mercury|promise_pure|thread_safe|does_not_affect_liveness|no_sharing|tabled_for_io|can_pass_as_mercury_type)</string>
							<key>name</key>
							<string>constant.language.proc_type.source.mercury</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#line_comment</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>#line_comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#variable</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#default_insts</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#type_name</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>string.quoted.double.source.mercury</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.source.mercury</string>
						</dict>
					</dict>
					<key>match</key>
					<string>("C#"|csharp|"C"|c|"Erlang"|erlang|"Java"|java|"IL"|il)[,][ \t]*[(]?([a-z][a-zA-Z0-9_\.]*)</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.source.mercury</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^[ \t]*[(]?([a-z][a-zA-Z0-9_\.]*)\b</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string_quoted_double</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>#decl_keywords</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^[a-z][a-zA-Z0-9_\.]*\b</string>
			<key>name</key>
			<string>entity.name.function.source.mercury</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#logic_consts</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#variable</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b[a-z][a-zA-Z0-9_]*\b</string>
			<key>name</key>
			<string>constant.other.symbol.source.mercury</string>
		</dict>
		<dict>
			<key>match</key>
			<string>[$][a-zA-Z0-9_]*\b</string>
			<key>name</key>
			<string>variable.language.source.mercury</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>decl_keywords</key>
		<dict>
			<key>match</key>
			<string>\b(pred|func|is|where)\b</string>
			<key>name</key>
			<string>keyword.control.declaration.source.mercury</string>
		</dict>
		<key>default_insts</key>
		<dict>
			<key>match</key>
			<string>\b(in|out|ui|di|uo)\b</string>
			<key>name</key>
			<string>constant.language.inst.source.mercury</string>
		</dict>
		<key>determ_decl</key>
		<dict>
			<key>match</key>
			<string>\b(multi|cc_multi|det|semidet|nondet|errorneous)\b</string>
			<key>name</key>
			<string>constant.language.determ.source.mercury</string>
		</dict>
		<key>line_comment</key>
		<dict>
			<key>begin</key>
			<string>(^[ \t]+)?(?=%)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.whitespace.comment.leading.source.mercury</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?!\G)</string>
			<key>name</key>
			<string>comment.line.percentage.source.mercury</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>%</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.source.mercury</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=\n)</string>
				</dict>
			</array>
		</dict>
		<key>logic_consts</key>
		<dict>
			<key>match</key>
			<string>\b(yes|no|true|false)\b</string>
			<key>name</key>
			<string>constant.language.logic.source.mercury</string>
		</dict>
		<key>string_quoted_double</key>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.literal.string.begin.source.mercury</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.literal.string.end.source.mercury</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.source.mercury</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.source.mercury</string>
				</dict>
				<dict>
					<key>match</key>
					<string>""</string>
					<key>name</key>
					<string>constant.character.escape.quote.source.mercury</string>
				</dict>
			</array>
		</dict>
		<key>type_name</key>
		<dict>
			<key>match</key>
			<string>\b([a-z][_\.a-zA-Z0-9]*)\b</string>
			<key>name</key>
			<string>support.type.source.mercury</string>
		</dict>
		<key>variable</key>
		<dict>
			<key>match</key>
			<string>\b[A-Z][a-zA-Z0-9_]*\b</string>
			<key>name</key>
			<string>variable.other.source.mercury</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.mercury</string>
	<key>uuid</key>
	<string>A3E186F8-CF20-4983-B132-209EDF43E3DE</string>
</dict>
</plist>
