<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>m</string>
		<string>moo</string>
	</array>
	<key>name</key>
	<string>Mercury</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#number</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#string_quoted_double</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#inline_bin_op</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#atom</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#block_comment</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#line_comment</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#decl_keywords</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#purity_level</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#declarations</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#common_ops</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#determ_keywords</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#logic_keywords</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#foreign_mods</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#variables</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>atom</key>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.source.mercury</string>
				</dict>
			</dict>
			<key>end</key>
			<string>'(?!['])</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.source.mercury</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.single.source.mercury</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.source.mercury</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\'\'</string>
					<key>name</key>
					<string>constant.character.escape.quote.source.mercury</string>
				</dict>
			</array>
		</dict>
		<key>block_comment</key>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.source.mercury</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.source.mercury</string>
		</dict>
		<key>common_ops</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(-(?![&gt;-])|[+](?![+])|[*][*]?|/(?![\\/])|//|\\(?![/=]))</string>
					<key>name</key>
					<string>keyword.operator.arithmetic.source.mercury</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(=&lt;|&gt;=|&lt;(?![=])|(?![-])&gt;)</string>
					<key>name</key>
					<string>keyword.operator.comparison.source.mercury</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(&lt;=&gt;|&lt;=|=&gt;|\\=|==|:-|=(?![=&lt;&gt;])|,|;|-&gt;|/\\(?![=])|\\/|@)</string>
					<key>name</key>
					<string>keyword.operator.logic.source.mercury</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(--&gt;|---&gt;|[+][+](?![+])|::|:=|![\.:]?|\||\^)</string>
					<key>name</key>
					<string>keyword.operator.other.source.mercury</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(\(|\)|\[|\])</string>
					<key>name</key>
					<string>keyword.operator.list.source.mercury</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\.(?=[ \t]*($|%))</string>
					<key>name</key>
					<string>keyword.operator.terminator.source.mercury</string>
				</dict>
			</array>
		</dict>
		<key>decl_keywords</key>
		<dict>
			<key>match</key>
			<string>\b(is|where)\b</string>
			<key>name</key>
			<string>keyword.control.declaration.source.mercury</string>
		</dict>
		<key>declarations</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.logic.source.mercury</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?x)(^[ \t]*:-)[ ]((use|include|end|import|)_module|module |func|pred|type(class)?|inst(ance)? |mode|interface|implementation )\b</string>
					<key>name</key>
					<string>keyword.control.declaration.source.mercury</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.logic.source.mercury</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.control.pragma.source.mercury</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?x)(^[ \t]*:-)[ ](pragma)[ ](check_termination|does_not_terminate|fact_table |inline|loop_check|memo|minimal_model|no_inline |obsolete|promise_equivalent_clauses|source_file |terminates|type_spec |foreign_(proc|type|decl|code|export(_enum)? |enum|import_module) )\b</string>
					<key>name</key>
					<string>constant.language.pragma.source.mercury</string>
				</dict>
			</array>
		</dict>
		<key>determ_keywords</key>
		<dict>
			<key>match</key>
			<string>(?x)\b(require_(_switch_arms)?)?(multi|cc_(multi|nondet) |det|semidet|nondet |errorneous|failure )\b</string>
			<key>name</key>
			<string>constant.language.determ.source.mercury</string>
		</dict>
		<key>foreign_mods</key>
		<dict>
			<key>match</key>
			<string>(?x)\b(affects_liveness|(does_not|doesnt)_affect_liveness |attach_to_io_state |can_pass_as_mercury_type|stable |(may_call|will_not)(_call_mercury|_modify) |(may_)(not_)?_duplicate |(no_|unknown_)?sharing|tabled_for_io|local |(un)?trailed |(not_|maybe_)?thread_safe |will_not_throw_exception )\b</string>
			<key>name</key>
			<string>storage.type.source.mercury</string>
		</dict>
		<key>impl_defined_variable</key>
		<dict>
			<key>match</key>
			<string>[$][a-zA-Z0-9_]*\b</string>
			<key>name</key>
			<string>variable.language.source.mercury</string>
		</dict>
		<key>inline_bin_op</key>
		<dict>
			<key>match</key>
			<string>`[^`]+`</string>
			<key>name</key>
			<string>keyword.operator.other.source.mercury</string>
		</dict>
		<key>line_comment</key>
		<dict>
			<key>begin</key>
			<string>(^[ \t]+)?(%([-]+%)?)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.whitespace.comment.leading.source.mercury</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>comment.line.percentage.source.mercury</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?!\G)</string>
			<key>name</key>
			<string>comment.comment.source.mercury</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.note.source.mercury</string>
						</dict>
					</dict>
					<key>match</key>
					<string>[ \t]+(XXX|TODO|FIXME|WARNING|NOTE|Note:)\b</string>
				</dict>
				<dict>
					<key>match</key>
					<string>.*</string>
				</dict>
			</array>
		</dict>
		<key>logic_keywords</key>
		<dict>
			<key>match</key>
			<string>(?x)\b(yes|no|true|false|(semidet_)?succeed|(semidet_)?fail |some|all|require_complete_switch )\b</string>
			<key>name</key>
			<string>constant.language.logic.source.mercury</string>
		</dict>
		<key>number</key>
		<dict>
			<key>match</key>
			<string>\b(0(?!['])[0-7]*|0['].|[1-9][0-9]*|\.[0-9]+([eE][0-9]+)?|0[xX][0-9a-fA-F]+|0[bB][01]+)\b</string>
			<key>name</key>
			<string>constant.numeric.source.mercury</string>
		</dict>
		<key>purity_level</key>
		<dict>
			<key>match</key>
			<string>\b((promise_)(semi)?pure|(im|semi)?pure)\b</string>
			<key>name</key>
			<string>storage.type.source.mercury</string>
		</dict>
		<key>singleton_variable</key>
		<dict>
			<key>match</key>
			<string>\b_[A-Z]?[a-zA-Z0-9_]*\b</string>
			<key>name</key>
			<string>support.variable</string>
		</dict>
		<key>string_quoted_double</key>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.literal.string.begin.source.mercury</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"(?!")</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.literal.string.end.source.mercury</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.source.mercury</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.source.mercury</string>
				</dict>
				<dict>
					<key>match</key>
					<string>""</string>
					<key>name</key>
					<string>constant.character.escape.quote.source.mercury</string>
				</dict>
				<dict>
					<key>match</key>
					<string>%[I]?[-+# *\.0-9]*[dioxXucsfeEgGp]</string>
					<key>name</key>
					<string>constant.character.escape.format.source.mercury</string>
				</dict>
			</array>
		</dict>
		<key>variable</key>
		<dict>
			<key>match</key>
			<string>\b[A-Z][a-zA-Z0-9_]*\b</string>
			<key>name</key>
			<string>variable.other</string>
		</dict>
		<key>variables</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#impl_defined_variable</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#singleton_variable</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#variable</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.mercury</string>
	<key>uuid</key>
	<string>A3E186F8-CF20-4983-B132-209EDF43E3DE</string>
</dict>
</plist>
